### ISSUE TITLE
Gauge.CSharp.Runner is locking gauge.dll

### ISSUE THREAD

**Issue by pmcphailWAT** [getgauge/gauge-vscode#241]
I've noticed this error occurring when I stop the execution of my test and then attempt to run a test again.  I'm using VScode:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4106,5): error MSB3027: Could not copy "obj\Any CPU\Debug\tkgauge.dll" to "c:\tkgauge\gauge_bin\tkgauge.dll". Exceeded retry count of 10. Failed. The file is locked by: "Gauge.CSharp.Runner (29680)" [C:\tkgauge\tkgauge.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4106,5): error MSB3021: Unable to copy file "obj\Any CPU\Debug\tkgauge.dll" to "c:\tkgauge\gauge_bin\tkgauge.dll". The process cannot access the file 'c:\tkgauge\gauge_bin\tkgauge.dll' because it is being used by another process. [C:\tkgauge\tkgauge.csproj]
```
If  I end the process Gauge.CSharp.Runner.exe, I can run tests again.

Here is a screen shot of the button in VSCode that I use to stop execution:
![stoptest](https://user-images.githubusercontent.com/28151825/39058695-2e303d72-4482-11e8-9f0d-a678168b5ae3.PNG)

```
VS-Code version: 1.22.2
Gauge Extension Version: 0.0.3

Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
csharp (0.10.3)
html-report (4.0.3)
screenshot (0.0.1)
```

**Comment by sriv** [comment]
So, we do not have support for gauge+csharp+vscode yet. Please follow [this issue](https://github.com/getgauge/gauge-vscode/issues/84) for updates.

Guessing from the screenshot, I believe the OS is windows. Please correct if me if I am wrong.

We have made a good amount of changes to gauge, and gauge-vscode. If you could try the latest nightly builds of both, and let us know if there is any improvement, it would be great.

Here are the download links:

gauge nightly: https://bintray.com/gauge/Gauge/Nightly/_latestVersion
gauge-vscode nightly: https://bintray.com/gauge/gauge-vscode/Nightly/_latestVersion

### Dev Notes

- This is possibly because on `Stop Execution` command in gauge-vscode, the child gauge process is killed. `Gauge.CSharp.Runner.exe` is a child process of `Gauge` which isn't getting killed automatically. Windows does not kill process trees automatically, like *nix.

- We did add a fix, by making `Gauge.CSharp.runner` poll for parent process's state, and kill itself. Need to investigate why this isn't working.

**Comment by pmcphailWAT** [comment]
I installed the latest vscode nightly build. So far it appears that the issue is fixed.  I have not been able to recreate the issue on the latest build. I will continue to run a few more tests.
