### ISSUE TITLE
[dotnet] Stopping the execution should terminate debugging gracefully

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#278]
**Actual behavior**
Getting an exception
<img width="468" alt="screen shot 2018-07-20 at 2 54 49 pm" src="https://user-images.githubusercontent.com/6310197/42994949-2c743716-8c2d-11e8-9322-54ff0298ff7f.png">

**Steps to replicate**
* Create a gauge-dotnet project
* Start debugging with a break point
* When a breakpoint is hit Stop `Running the specs` from the panel below
<img width="593" alt="screen shot 2018-07-20 at 2 59 25 pm" src="https://user-images.githubusercontent.com/6310197/42995078-8967c208-8c2d-11e8-839d-fb2bec93dd83.png">
> The above exception is seen

**Version**
```
https://bintray.com/gauge/gauge-dotnet/Nightly/0.1.1.nightly-2018-07-19
```
Blocks #279

**Comment by BugDiver** [comment]
The ideal way to stop the debugger is using the vscode's debug UI (the disconnect button).
Stopping the debugger from the UI works as expected.
The  `Running the specs` is mostly for providing a way to stop the gauge execution.

This status bar should not be shown while debugging since canceling an execution is kind of disrupting the debug session.
