### ISSUE TITLE
Should be able to run with multiple env configurations

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#289]
**Proposed behavior**
From the IDE, the user should be able to run specifying multiple environments

**Current behavior**
Able to run with the default configuration.

For further details, please refer https://github.com/getgauge/gauge/issues/1109

**Comment by Vaahin** [comment]
Is there any update on this feature ?

**Comment by zabil** [comment]
No updates for this at the moment.

**Comment by DvagNic** [comment]
Alternatively it would be nice if the env variables could be specified as a setting for this extension. Then you could just append the envs to the gauge call:
`gauge run <myspec> --simple-console --hide-suggestion --env <hardcoded_envs_from_extension_settings>`

**Comment by zabil** [comment]
To make this generic Gauge VS Code plugin must add the commands
* Run all specifications (with arguments)
* Run scenario (with arguments)
* Run scenarios (with arguments)

That will accept a set of arguments as input before running specifications or scenarios.

**Comment by guntribam** [comment]
This will be a nice feature to have? Can i help in some way @zabil ?

**Comment by zabil** [comment]
Yes, a PR would be awesome.

A good start would be to read a value from the gauge vs code plugin settings. Adding a key called 
```
 gauge.execution.args: --env dev,
```

You can set that [here](https://github.com/getgauge/gauge-vscode/blob/59ee8cfe1fdd0428af6e4f8e95ff01802c4f4909/package.json#L211) and read it from the [executor](https://github.com/getgauge/gauge-vscode/blob/59ee8cfe1fdd0428af6e4f8e95ff01802c4f4909/src/execution/gaugeExecutor.ts#L210)

**Comment by at6ue** [comment]
This issue and #221 could be solved in the same way.
While @zabil suggested adding the property in `settings.json`, @sguptatw proposed having the properties in `launch.json`.
Which do you think is preferable?

The latter is probably similar to [the case of Python plugin](https://code.visualstudio.com/docs/python/testing#_debug-tests).

>To customize settings for debugging tests, you can specify "request":"test" in the launch.json file in the .vscode folder from your workspace. This configuration will be used when you run Python: Debug All Tests and Python: Debug Test Method commands.
>...
>If you have more than one configuration entry with "request":"test", the first definition will be used since we currently don't support multiple definitions for this request type.

Because the debug configuration with `"request":"test"` is only for the setup, users will get an error message if they run with it from "Run and Debug" pane.

IMHO, it is better to have the properties in `launch.json` if you consider assigning properties to *each* `run` argument.
Having only `gauge.execution.args` as @zabil suggested is simple but instead users should know what kind of arguments are available.

If you are working on this I will leave it to you @guntribam. How is it?
Actually what I want is `tags` option though, I think I can implement others as well.

**Comment by guntribam** [comment]
i'm not working on this... @at6ue

**Comment by zabil** [comment]
> IMHO, it is better to have the properties in launch.json if you consider assigning properties to each run argument.
Having only gauge.execution.args as @zabil suggested is simple but instead users should know what kind of arguments are available.

I agree that `launch.json` is a better way to manage this. I recommended `settings.json` because environment settings usually don't change much for example a `dev` environment on the developer machine. But then that is specific to only environments. Using a `launch.json` a user can set the environment and other parameters like #221

**Comment by sriv** [comment]
+1 to `launch.json`, I believe `launch.json` is idiomatic way to configure execution whereas `settings.json` can be for user settings/project settings.

@at6ue - please feel free to raise a PR for this.

**Comment by at6ue** [comment]
> `settings.json` can be for user settings/project settings.

I agree with this. I will send a PR in a few weeks.

**Comment by at6ue** [comment]
Remind: This issue should be able to be closed now that #736 has been released.

**Comment by sschulz92** [comment]
Is there any example how to use this cool feature? :) Thank you in advance!

**Comment by at6ue** [comment]
@sschulz92 
As documented [here](https://github.com/getgauge/gauge-vscode#run-and-debug-configuration), you can specify `gauge run` options in your launch.json. 
The video in #736 might help you to add your first configuration to launch.json. Then add properties to it, like `”env”: [“filename”]`.

Enjoy :)
