### ISSUE TITLE
Gauge executable not found!

### ISSUE THREAD

**Issue by masoud-bahrami** [getgauge/gauge-vscode#352]
I installed gauge extension on vs code.
When  i open any dotnet gauge project, welcome page will be fired.
But i run into "Gauge executable not found" problem.
And also in my spec files i can't go to the spec implementations.

**Comment by nickmorton** [comment]
I'm seeing the same issue with the latest release 0.0.7, but not when I debug the latest code. I believe this has been fixed in #290 which is not yet released. Essentially it switches to use gauge.cmd to run gauge.

**Comment by NivedhaSenthil** [comment]
@nickmorton  Thanks for pointing out #290 is yet to be released. Meanwhile you can try using nightly version of gauge-vscode plugin which can be downloaded from [here](https://bintray.com/gauge/gauge-vscode)

**Comment by nickmorton** [comment]
> @nickmorton Thanks for pointing out #290 is yet to be released. Meanwhile you can try using nightly version of gauge-vscode plugin which can be downloaded from [here](https://bintray.com/gauge/gauge-vscode)

Thanks - already done it!

**Comment by zabil** [comment]
@masoud-bahrami we don't do product roadmaps. There are many articles like [this](https://medium.com/@eugenesanu/the-problem-with-product-roadmaps-fd3a40090f7c) one that explain why they fail. 

Please reach out to us if you are interested in signing up for research to help build the product instead.

**Comment by masoud-bahrami** [comment]
@zabil Yes you alright. Actually  By road-map I meant the Major version changes of the Gauge.

In one of my current projects as a tech lead i used Gauge to automate SBEs for a DDD and Microservices based project in dotnet platform.

Yes I interested if i can participate in Gauge path.

**Comment by zabil** [comment]
>  Major version changes of the Gauge.

If you meant release notes they are here https://github.com/getgauge/gauge/releases

**Comment by CreeTar** [comment]
This issue is still not fixed. I also get the 'Gauge executable not found! Click here for install instructions.' and all you do is link to the website of Gauge where not informations can be found. 
Basically telling people to google is not the way to go. How about you explain the user how he can tell you where to find the executable, since the problem here is the extension not Gauge. If you do not offer any sort of configuration to define the location of the executable, well no wonder you won't be lucky by just looking at GAUGE_ROOT. This should be fixed, VSCode does not need admin to run, but if you now need to set GAUGE_ROOT manually each time in terminal just so you can find the executable? Not very practical at all.

**Comment by zabil** [comment]
> and all you do is link to the website of Gauge where absolutely no informations can be found about this issue,

The documentation site has gone through an upgrade the link will be fixed in the next release meanwhile, for reference, installation instructions are here https://docs.gauge.org/getting_started/installing-gauge.html

Also, for the benefit of others, please feel free to improve the documentation using "Edit" and sending a pull request.

> If you do not offer any sort of configuration to define the location of the executable, well no wonder you won't be lucky by just looking at GAUGE_ROOT.

GAUGE_ROOT need not be configured it's just enough to add have the folder where Gauge is installed in the PATH variable. This should pick up whenever you launch VS Code.

> VSCode does not need admin to run, but if you now need to set GAUGE_ROOT manually each time in terminal just so you can find the executable? Not very practical at all.

Can you create another issue for this feature? It's should be possible to add a configuration to point to a custom installation location.
