### ISSUE TITLE
Default html report for the test execution should be generated when executed tests in VSCode

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge-vscode#354]
**Gauge version:** 1.0.4

**Commit Hash:** 3a9a647

**Plugins**
flash (0.0.1)
html-report (4.0.6)
java (0.7.2.nightly-2019-03-07)
js (2.3.2)
json-report (0.2.2)
python (0.3.4)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**OS:** Windows 10 64 bit

**VSCode version:** 1.31.1 (latest)

**Gauge plugin for VSCode:** 0.0.8 (latest)

**Steps to reproduce:**

1.  Create a new gauge java project (`gauge init java`)
2.  Import it to the VSCode
3.  Expand specs folder and Open a spec file
4.  Click on Run Spec or Run Scenario options in that spec file
5.  After the execution is completed, navigate to **reports/html-report**
6.  Open index.html

**Actual:**
Html report is differed from the default html-report

**Expected:**
Default html-report should be generated for the test execution triggered in VSCode. User should be able to open it.

**Screenshot:**
![image](https://user-images.githubusercontent.com/9147189/54337409-d66a5200-4654-11e9-9757-f7500f48ce34.png)

**Comment by zabil** [comment]
Related to https://github.com/getgauge/gauge-vscode/issues/350

**Comment by nehashri** [comment]
@osandadeshan This is intentional. When tests are run in VSCode, a different template is used to generate the html report. This template is optimized for the best view on VSCode. You can view the report by executing `Gauge: Show Last Run Report` from VSCode's command pallet or by clicking on the spec, scenario execution result status in VSCode's status bar. 
<img width="210" alt="Screenshot 2019-03-14 at 12 46 36 PM" src="https://user-images.githubusercontent.com/5715387/54338202-3b26ac00-4657-11e9-9ba0-68053ba4af43.png">

**Comment by osandadeshan** [comment]
@zabil Yes that will be helpful. But it will be much helpful to the automation engineers if gauge can generate the default report because it contain more data which will be useful.

**Comment by AMWatty** [comment]
I'd like the choice to generate the gauge framework default report rather than the gauge-plugin report.

**Comment by zabil** [comment]
Yes.
The behaviour will change in the next release. On clicking the summary of the test run in the status bar in VS Code. It will open a browser which will display the gauge default report.

**Comment by osandadeshan** [comment]
@zabil Great. Thanks.

**Comment by Debashis9012** [comment]
This has been verified and found fixed. Tested with the below version:
``` gauge-0.0.10.nightly-2019-04-04.vsix ```
