### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by nedaashrafi** [getgauge/gauge-vscode#372]
I made a c# project using command `gauge init csharp `and I opened it in VS Code. I installed gauge extension but in command pallette I don't have all the commands. I just have two commands which you can see in this photo:

![alt text](http://uupload.ir/files/5r2n_image.png)

Also, when I run this two commands, I received this message:

> command 'gauge.createProject' not found

In **exmaple.spec** , I don't have `Run scenarios & debug scenarios` .
![alt text](http://uupload.ir/files/h53c_image2.png)

I repeated these steps with a **JavaScript** sample, but I still have the similare problems.

_My OS on my computer is Windows10._

**Comment by nehashri** [comment]
@nedaashrafi We don't support C# with .NET Framework on VSCode. However, if you want to install C# with .NET Core instead, please use `gauge init dotnet`. 

The JavaScript sample should have worked. There may have been some error due to which it hasn't worked for you. 
Can you please let us know which version of Gauge extension is installed in VSCode? 
How was Gauge installed in your machine(what commands were used)?
Also, please run `gauge -v` on the command line and paste its contents here.

Please check if there are any errors that are reported in `lsp.log` file in the logs folder of your project, if you find any, let us know.

**Comment by mattimatt** [comment]
I see the same behavior on windows 10, with dotnet and vscode extension version 0.0.9.
I have:

Visual Studio Code
----
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Gauge
----
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
csharp (0.10.5)
dotnet (0.1.1)
html-report (4.0.8)
screenshot (0.0.1)
xml-report (0.2.1)

using version 0.0.8 of the vscode extension does work as expected.
additionally running gauge in the terminal (bash MINGW64), e.g. gauge -v, results in 
```
/c/Users/xxxxx/AppData/Roaming/npm/gauge: line 1: /node_modules/@getgauge/cli/bin/gauge: No such file or directory
```
while running it from the normal command line works fine. mountebank runs fine using either bash or cmd.

**Comment by NivedhaSenthil** [comment]
VScode 0.0.10 is released now, can you please verify if it works with the latest ?

**Comment by mattimatt** [comment]
Yes indeed 0.0.10 is ok, thnx!
I have added https://github.com/getgauge/gauge/issues/1416 for the bash issue.
