### ISSUE TITLE
Can not debug with Python project

### ISSUE THREAD

**Issue by max90727** [getgauge/gauge-vscode#381]
**Expected behavior**
User should be able to debug the spec.

**Actual behavior**
Getting error `use of closed network connection`

**My setup:**
Visual Studio Code
Version: 1.34.0 (user setup)
Node.js: 10.2.0

Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.6)
python (0.3.4)
screenshot (0.0.1)

**Comment by shubhamsc** [comment]
@max90727 There was an issue with python debugging in vs code https://github.com/getgauge/gauge-python/issues/110 which is fixed in latest python release version. 
upgrade the python plugin to `0.3.5`. Debugging should work fine.
Let's us know if you are facing the same issue after update to the latest version.

**Comment by max90727** [comment]
@shubhamsc 0.3.5 is working. Thank you.
