### ISSUE TITLE
Create a simple JS project when JS is choosen as language

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-vscode#386]
When creating a new javascript project create a simple js project instead of the taiko js.

Steps:
1. from command palate `Gauge: Create a new Gauge Project`
2. select `js`

**Comment by zabil** [comment]
On second thoughts. We must try to initialise a web testing application as much as possible. This is because we are targeting web applications. It's best we modify the documentation to state that the sample project will open a browser. 

Generating a vowels example is too basic and converting it to a web testing project is not easy.
@luciferankon please revert the change.

**Comment by BugDiver** [comment]
The commit has been reverted. Closing the issue since there is no scenario to test,
