### ISSUE TITLE
Implement a test explorer for scenarios

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#42]
Use the Explorer feature is VS code to implement a test explorer.
For e.g. refer Gitlens plugin

![testexploere](https://user-images.githubusercontent.com/54427/32875671-400a059c-cabf-11e7-9136-b392c0c1fba2.gif)

* The pane must list all the Specifications (sorted by scenario heading). It must have a search and filter. The search must be fuzzy
* Clicking on the Specification must open the specification in the editor.
* The Specification can be run from the explorer

**Comment by zabil** [comment]
* Can we refresh the test explorer on save to avoid the test explorer pane going out of sync?
* Can we add a find icon that will popup search for symbols when command when clicked?

**Comment by sguptatw** [comment]
When does the test explorer open? - On which action
How can I open it manually?

**Comment by sriv** [comment]
@sguptatw  you need to set `gauge.specExplorer.enabled=true`. By default test explorer is hidden.

**Comment by Apoorva-GA** [comment]
Text explorer is visible by default now. We have made this change as part of [this](https://github.com/getgauge/gauge-vscode/commit/884c2d8771427fdb7bf27bd2ba31edb371a9da2b) commit.

**Comment by riju91** [comment]
it should be available in nightly >= 2017-01-16

**Comment by sguptatw** [comment]
**Issue**
Change and save the specification heading should reflect in the test explorer

**Expected behavior**
If the spec file is saved after changing the specification heading, the change should reflect in the test explorer.

**Actual behavior**
User settings -     "files.autoSave": "afterDelay"
Explicitly save the specification and close it. The test explorer does not refresh.

Should any other settings be enabled?

**Comment by sguptatw** [comment]
**Expected behavior**
With multiple projects in a workspace, all the specifications should be shown in the test explorer

**Actual behavior**
Adding multiple projects to the workspace does not show the corresponding specs in the test explorer.

**Steps to replicate**
* Create 2 gauge projects
* Add them to the workspace
* Only first project's specifications are listed

**Comment by sguptatw** [comment]
Allows adding the parent folder of a gauge project. But removing it gives an error
<img width="672" alt="description_undefined" src="https://user-images.githubusercontent.com/6310197/35027352-402588d4-fb76-11e7-8143-db9101f5fab4.png">

**Steps to replicate**
* In [LSP Tests](github.com/getgauge/gauge-lsp-tests). Open workspace `data\testdata.code-workspace`.
* Add folder `parse-errors`.
* Remove `parse-errors` from the workspace.
> Note the error

**Version**
VSCode - gauge-0.0.4.nightly-2018-01-16.vsix

**Comment by sguptatw** [comment]
**Issue**
Run in the test explorer should not show the project list

**Expected behavior**
It should run the specifications from the project open in the test explorer.

**Version**
gauge-0.0.4.nightly-2018-01-16

**Comment by sguptatw** [comment]
**Issue**
Error on `esc` of project list
<img width="672" alt="description_undefined" src="https://user-images.githubusercontent.com/6310197/35027981-9d3cfeb4-fb79-11e7-9610-7829cbbefdc3.png">

**Expected behavior**
The project list should close

**Steps to replicate**
* On the test explorer click the `Change Project` item
* `esc`
>Note: Above error is displayed

Version
gauge-0.0.4.nightly-2018-01-16

**Comment by sguptatw** [comment]
**Expected behavior**
Selecting a specification on the test explorer should navigate to the specification heading of the corresponding spec

**Actual behavior**
It is going to the last/previously selected scenario in the specification.

**Version**
gauge-0.0.4.nightly-2018-01-16

**Comment by sguptatw** [comment]
**Expected behavior**
In the test explorer, I cannot select multiple scenarios. Right click on a scenario displayed in the test explorer should say `Run Scenario`

**Actual behavior**
It says `Run Scenarios`

**Version**
gauge-0.0.4.nightly-2018-01-16

**Comment by sguptatw** [comment]
**Expected behavior**
Running one project should not show errors from another project.

**Actual behavior**
Getting parse errors of a different project

**Steps to replicate**
* Create project `parse-errors`
* Create project `other`
* Add a circular reference error in project `parse-errors`
* Add both projects to workspace
* Run scenario from project `other`

>Note: The errors on the console. 

>Note: `Run Scenario` command from command palette is getting an error `Cannot read property uri of undefined`

**Comment by sguptatw** [comment]
Is Search and filter functionality out of scope of this story?

**Comment by sguptatw** [comment]
When a file of a given project is opened, can the test explorer show the corresponding project?

**Comment by zabil** [comment]
> Is Search and filter functionality out of scope of this story?

Yes, this will be handled separately

**Comment by sguptatw** [comment]
@riju91 - Can multiple select of specifications/scenarios will be handled?

**Comment by sguptatw** [comment]
Created an issue for Search in Test explorer - https://github.com/getgauge/gauge-vscode/issues/121

**Comment by riju91** [comment]
@sguptatw It seems that vscode has closed https://github.com/Microsoft/vscode/issues/1023 which means they have added a multi select. We need to explore if that is added to extension API as well
