### ISSUE TITLE
debugging window outside vscode / debug broken

### ISSUE THREAD

**Issue by sarut0bi** [getgauge/gauge-vscode#499]
Lately without any action of my own (i think) , the nodeJs window is opened in an external Window and not inside output tab.
Side effect of this is make debug impossible :/ 
I am a windows user

**Comment by zabil** [comment]
Thanks for reporting this is also mentioned at https://spectrum.chat/gauge/general/vscode-gauge-integration~d02b14fa-a855-4307-a8eb-b31585b94e3b

This issue happens only on windows because of this change https://github.com/getgauge/gauge-vscode/commit/ebcff0087a44fb725d4906a3d18d97b79e8ae1d1 Will be fixing it soon.

**Comment by zabil** [comment]
In the meanwhile use an earlier version of the Gauge VS Code plugin

**Comment by sarut0bi** [comment]
working as expected with rollback to `0.0.15` 
ty @zabil

**Comment by NivedhaSenthil** [comment]
0.0.17 is released with the breaking changed reverted
