### ISSUE TITLE
All steps show problems in VSCode editor

### ISSUE THREAD

**Issue by djrice** [getgauge/gauge-vscode#76]
Using the example generated taiko project, all steps show problems in editor along the lines of: 

`write tcp 127.0.0.1:49428->127.0.0.1:49434: use of closed network connection`

Also:
- Goto definition (from step) doesn't work
- Find references (from step implementation) doesn't work

```
VS-Code version: 1.18.1
Gauge Extension Version: 0.0.3

Gauge version: 0.9.6.nightly-2017-12-13
Commit Hash: 571fda8

Plugins
-------
html-report (4.0.2)
java (0.6.5)
js (2.0.2)
screenshot (0.0.1)

```

**Comment by sguptatw** [comment]
The js plugin version is old can you please update to the latest and check
* Download https://bintray.com/gauge/gauge-js/Nightly/2.0.3.nightly-2017-12-14
**For installation**
* gauge install -f <downloadedFile>

**Comment by djrice** [comment]
The install fails:

lumbertruck% gauge install -f gauge-js-2.0.3.nightly-2017-12-14.zip

File manifest.json doesn't exist.

**Comment by djrice** [comment]
The install fails:

```
% gauge install -f gauge-js-2.0.3.nightly-2017-12-14.zip
File manifest.json doesn't exist.
```

**Comment by zabil** [comment]
I think it's,

gauge install js -f file.zip


On 16 Dec 2017 12:30 am, "David Rice" <notifications@github.com> wrote:

The install fails:

% gauge install -f gauge-js-2.0.3.nightly-2017-12-14.zip
File manifest.json doesn't exist.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/getgauge/gauge-vscode/issues/76#issuecomment-352085045>,
or mute the thread

**Comment by djrice** [comment]
OK. That fixed the install.  But not the originally reported problem. Maybe I need to get on a screen share with one of you next week.

**Comment by djrice** [comment]
Actually, restarting everything made it work. So I guess the gauge process required a restart after the plugin upgrade?  You can close this issue.
