### ISSUE TITLE
Report results of a test run in the status bar

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#90]
Whenever specifications are run using commands like "Run All Specifications", "Run Scenario" etc from command palette or the code lenses. 

Summarize the as follows

* `22/P, 0/F, 0/S` where 22 is the number of scenarios passed, 0 is the number of scenarios failed, 0 is the number of scenarios skipped
* Colorize `22/P` as green `0/F` as red and `0/s` as yellow 

On clicking the status bar it must open the command palette with the options
* View report
* Re-run tests
* Re-run failed tests.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge and gauge-vscode nightly >= 12/02/18

**Comment by sguptatw** [comment]
**Test cases**
- [x] Status bar displays the information. Instead of P,F and s it shows a tickmark, crossmark and an exclamation mark.
- [x] Clicking the status bar opens the command palette with the mentioned options
- [x] View report opens the report in the browser
- [x] Re-run tests and Re-run failed tests work as expected

**Issues**
- Once an execution starts the previous status should get cleared from the status bar - https://github.com/getgauge/gauge-vscode/issues/139
